apiVersion: v2
name: sam-agent
description: A Helm chart for Solace Agent Mesh Custom Agents deployments in Kubernetes
type: application
version: 1.1.0
maintainers:
  - name: Solace
    email: info@solace.com
home: https://solace.com/products/agent-mesh/
