{{- if not .Values.global.persistence.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sam.fullname" . }}-s3
  labels:
    app.kubernetes.io/service: s3
    {{- include "sam.labels" . | nindent 4 }}
type: Opaque
data:
    S3_ENDPOINT_URL: {{ .Values.dataStores.s3.endpointUrl | b64enc }}
    S3_BUCKET: {{ .Values.dataStores.s3.bucketName | b64enc }}
    S3_ACCESS_KEY: {{ .Values.dataStores.s3.accessKey | b64enc }}
    S3_SECRET_KEY: {{ .Values.dataStores.s3.secretKey | b64enc }}
{{- end }}